export const GET_PAISES = "GET_PAISES";
export const POST_TRAER_ESTADOS_POR_PAIS = "POST_TRAER_ESTADOS_POR_PAIS";
export const POST_TRAER_CIUDADES_POR_ESTADO = "POST_TRAER_CIUDADES_POR_ESTADO";
export const POST_USER = "POST_USER";
